name: Atualizar BigQuery

on:
  schedule:
    - cron: "*/30 * * * *"  # Roda a cada 30 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install requests pandas google-cloud-bigquery

      - name: Executar script
        run: python api_clima.py  # arquivo com codigo python
