name: Atualizar BigQuery

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Roda a cada 30 minutos

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install requests pandas google-cloud-bigquery

      - name: Criar credenciais.json
        run: echo "$BIGQUERY_CREDENTIALS" > credenciais.json
        shell: bash
      
      - name: Executar script
        run: python seu_script.py
