name: Atualizar BigQuery

on:
  workflow_dispatch: # Permite execução manual
  schedule:
    - cron: "*/30 * * * *" # Executa a cada 30 minutos

jobs:
  update_bigquery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Criar credenciais.json
        run: echo '${{ secrets.BIGQUERY_CREDENTIALS }}' | base64 --decode > credenciais.json

      - name: Verificar se credenciais foram criadas
        run: ls -l credenciais.json && cat credenciais.json

      - name: Configurar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script
        run: python api_clima.py
